---
- name: "Managing dotfiles"
  hosts: all
  become: true

  handlers:
    - name: update-grub
      command: grub-mkconfig -o /boot/grub/grub.cfg

    - name: copy-gtk-theme-temp
      copy:
        src: "/tmp/gtk-master/"
        dest: "/home/albert/.themes/Dracula/"
        remote_src: true
      become: false

    - name: compile-dwm
      make:
        chdir: "/home/albert/.dwm"
        target: install
      become: true

    - name: spicetify-apply
      shell: spicetify backup apply

  tasks:
    - import_tasks: packages.yml

    - include_tasks: dotfiles.yml
      loop: "{{ modules }}"
      loop_control:
        loop_var: module

    - import_tasks: extra.yml
      become: false

