---
- name: "Managing dotfiles"
  hosts: all
  become: true

  handlers:
    - name: update-grub
      command: update-grub

    - name: copy-gtk-theme-temp
      copy:
        src: "/tmp/gtk-master/"
        dest: "/home/albert/.themes/Dracula/"
        remote_src: true
      become: false

  tasks:
    - import_tasks: packages.yml

    - include_tasks: dotfiles.yml
      loop: "{{ modules }}"
      loop_control:
        loop_var: module

    - import_tasks: extra.yml
      become: false

