---
- name: "Managing dotfiles"
  hosts: all
  become: true

  roles:
    - luizgavalda.aur

  tasks:
    - import_tasks: packages.yml

    - include_tasks: dotfiles.yml
      loop: "{{ modules }}"
      loop_control:
        loop_var: module

